# ReadTheDocs environment customization to allow us to use conda to install
# libraries which have C dependencies for the doc build. See:
# https://docs.readthedocs.io/en/latest/config-file/v2.html

version: 2

sphinx:
  configuration: docs/conf.py

python:
  version: 3.8
  install:
    - pip: 
      - sphinx
      - sphinx-autodoc-typehints