# ReadTheDocs environment customization to allow us to use conda to install
# libraries which have C dependencies for the doc build. See:
# https://docs.readthedocs.io/en/latest/config-file/v2.html

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"


python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt


sphinx:
  configuration: docs/conf.py