name: Daily Sync with Botocore

on:
  schedule:
    # Every Monday to Friday at 10:00 UTC (3:00 PDT)
    - cron: 00 10 * * 1-5

jobs:
  sync-with-botocore:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Run CodeBuild
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: sagemaker-core-botocore-sync
  
